---
title: "HW4"
author: "Sarah Stover"
date: "2025-02-05"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Question 1

```{r}
x <- 1
a <- 2.2 
b <- 3.3

z = x^a^b 
print(z) 
z = (x^a)^b
print(z) 
z = (3*x)^3 + (2*x)^2 + 1
print(z) 

```
Question 2 
a) 
```{r}
c(seq(1,8), seq(7,1))
```
b) 
```{r}
rep(x = seq(1:5), times = seq(1:5))  
```
c) 
```{r}
rep(x = seq(5,1), times = seq(1,5))
```

Question 3
```{r}
x = runif(1)
y = runif(1) 

yx <- y/x
r <- sqrt(x^2 + y^2)
theta <- atan(yx) 

```

Question 4
```{r}
queue <- c("sheep", "fox", "owl", "ant")

```
a) 
```{r}
queue <- c(queue, "serpent")
print(queue)

```
b)
```{r}
queue <- queue[-1]
print(queue)
```
c)
```{r}
queue <- c("donkey", queue)
print(queue)
```
d)
```{r}
queue <- queue[-c(5)]
print(queue)
```
e)
```{r}
queue <- queue[-c(3)]
print(queue)
```
f) 
```{r}
queue <- c(queue[1:2], "aphid", queue[3])
print(queue)
```
d)
```{r}
which(queue == "aphid")
print(queue)
```
Question 5
```{r}
sequence <- seq(1:100)
filtered_seq <- sequence[!(sequence %% 2 == 0 | sequence %% 3 == 0 | sequence %% 7 == 0)]

```
